spring:
  application:
    name: cosy

jwt:
  secret: ${JWT_SECRET:1RUb2tlbkdlbmVyYXRpb25BbmRWYWxpZGF0aW9u}
  issuer: ${JWT_ISSUER:cosy}
  access-token-expiration: 10800000 # 1 hour
  refresh-token-expiration: 604800000 # 7 days
